// Code generated by "stringer -type Opcode enum.go"; DO NOT EDIT

package virtual

import "fmt"

const _Opcode_name = "NopAPAddF64AddI32AddPtrAddPtrsAddSPAnd32And8Argument32Argument64Argument8ArgumentsArgumentsFPBPBoolI32BoolI64BoolI8CallCallFPConvF32F64ConvF64F32ConvF64I32ConvF64I8ConvI32F32ConvI32F64ConvI32I16ConvI32I64ConvI32I8ConvI64I32ConvI8I32ConvI8I64ConvU16I32ConvU32I64ConvU8I32CopyDSDSI32DSI64DivF64DivI32DivU64Dup32Dup64EqI32EqI64ExtFloat32Float64FuncGeqI32GeqU64GtI32GtI64GtU32GtU64IndexIndexI32Int32Int64JmpJnzJzLabelLeqI32Load16Load32Load64Load8LshI32LtI32LtU64MulF64MulI32NegI32NeqI32NeqI64NotOr32PanicPostIncI32PostIncI8PostIncPtrPreIncI32PreIncI8PreIncPtrPtrDiffRemU64ReturnRshI32RshI8Store16Store32Store64Store8StoreBits8SubF64SubI32TextVariable32Variable64Variable8Xor32Zero32Zero64abortacosasinatanceilcoscoshexitexpfabsfclosefgetcfgetsfloorfopenfprintffreadfwriteloglog10memcmpmemcpymemsetpowprintfroundsinsinhsprintfsqrtstrcatstrchrstrcmpstrcpystrlenstrncmpstrncpystrrchrtantanhtolower"

var _Opcode_index = [...]uint16{0, 3, 5, 11, 17, 23, 30, 35, 40, 44, 54, 64, 73, 82, 93, 95, 102, 109, 115, 119, 125, 135, 145, 155, 164, 174, 184, 194, 204, 213, 223, 232, 241, 251, 261, 270, 274, 276, 281, 286, 292, 298, 304, 309, 314, 319, 324, 327, 334, 341, 345, 351, 357, 362, 367, 372, 377, 382, 390, 395, 400, 403, 406, 408, 413, 419, 425, 431, 437, 442, 448, 453, 458, 464, 470, 476, 482, 488, 491, 495, 500, 510, 519, 529, 538, 546, 555, 562, 568, 574, 580, 585, 592, 599, 606, 612, 622, 628, 634, 638, 648, 658, 667, 672, 678, 684, 689, 693, 697, 701, 705, 708, 712, 716, 719, 723, 729, 734, 739, 744, 749, 756, 761, 767, 770, 775, 781, 787, 793, 796, 802, 807, 810, 814, 821, 825, 831, 837, 843, 849, 855, 862, 869, 876, 879, 883, 890}

func (i Opcode) String() string {
	if i < 0 || i >= Opcode(len(_Opcode_index)-1) {
		return fmt.Sprintf("Opcode(%d)", i)
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
