// Code generated by "stringer -type Opcode enum.go"; DO NOT EDIT

package virtual

import "fmt"

const _Opcode_name = "NopAPAddF64AddI32AddPtrAddPtrsAddSPAnd32Argument32Argument64Argument8ArgumentsBPBoolI64CallConvF32F64ConvF64F32ConvF64I32CopyConvF64I8ConvI32F32ConvI32F64ConvI32I64ConvI32I8ConvI64I32ConvI8I32DSDivF64DivI32DivU64Dup32Dup64EqI32EqI64ExtFloat32Float64FuncGeqI32GtI32IndexIndexI32Int32Int64JmpJnzJzLabelLeqI32Load32Load64Load8LtI32MulF64MulI32NeqI32NeqI64Or32PanicPostIncI32PostIncPtrRemU64ReturnStore32Store64Store8SubF64SubI32TextVariable32Variable64Variable8Xor32Zero32Zero64abortacosasinatanceilcoscoshexitexpfabsfclosefgetcfgetsfloorfopenfreadfwriteloglog10memcmpmemcpymemsetpowprintfroundsinsinhsprintfsqrtstrcatstrchrstrcmpstrcpystrlenstrncmpstrncpystrrchrtantanh"

var _Opcode_index = [...]uint16{0, 3, 5, 11, 17, 23, 30, 35, 40, 50, 60, 69, 78, 80, 87, 91, 101, 111, 121, 125, 134, 144, 154, 164, 173, 183, 192, 194, 200, 206, 212, 217, 222, 227, 232, 235, 242, 249, 253, 259, 264, 269, 277, 282, 287, 290, 293, 295, 300, 306, 312, 318, 323, 328, 334, 340, 346, 352, 356, 361, 371, 381, 387, 393, 400, 407, 413, 419, 425, 429, 439, 449, 458, 463, 469, 475, 480, 484, 488, 492, 496, 499, 503, 507, 510, 514, 520, 525, 530, 535, 540, 545, 551, 554, 559, 565, 571, 577, 580, 586, 591, 594, 598, 605, 609, 615, 621, 627, 633, 639, 646, 653, 660, 663, 667}

func (i Opcode) String() string {
	if i < 0 || i >= Opcode(len(_Opcode_index)-1) {
		return fmt.Sprintf("Opcode(%d)", i)
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
