// Copyright 2017 The Virtual Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package virtual

func init() {
	registerBuiltins(map[int]Opcode{
		dict.SID("_beginthreadex"):              _beginthreadex,
		dict.SID("_endthreadex"):                _endthreadex,
		dict.SID("_msize"):                      _msize,
		dict.SID("AreFileApisANSI"):             AreFileApisANSI,
		dict.SID("CloseHandle"):                 CloseHandle,
		dict.SID("CreateFileA"):                 CreateFileA,
		dict.SID("CreateFileW"):                 CreateFileW,
		dict.SID("CreateFileMappingA"):          CreateFileMappingA,
		dict.SID("CreateFileMappingW"):          CreateFileMappingW,
		dict.SID("CreateMutexW"):                CreateMutexW,
		dict.SID("DeleteCriticalSection"):       DeleteCriticalSection,
		dict.SID("DeleteFileA"):                 DeleteFileA,
		dict.SID("DeleteFileW"):                 DeleteFileW,
		dict.SID("EnterCriticalSection"):        EnterCriticalSection,
		dict.SID("FlushFileBuffers"):            FlushFileBuffers,
		dict.SID("FlushViewOfFile"):             FlushViewOfFile,
		dict.SID("FormatMessageA"):              FormatMessageA,
		dict.SID("FormatMessageW"):              FormatMessageW,
		dict.SID("FreeLibrary"):                 FreeLibrary,
		dict.SID("GetCurrentProcessId"):         GetCurrentProcessId,
		dict.SID("GetCurrentThreadId"):          GetCurrentThreadId,
		dict.SID("GetDiskFreeSpaceA"):           GetDiskFreeSpaceA,
		dict.SID("GetDiskFreeSpaceW"):           GetDiskFreeSpaceW,
		dict.SID("GetFileAttributesA"):          GetFileAttributesA,
		dict.SID("GetFileAttributesW"):          GetFileAttributesW,
		dict.SID("GetFileAttributesExW"):        GetFileAttributesExW,
		dict.SID("GetFileSize"):                 GetFileSize,
		dict.SID("GetFullPathNameA"):            GetFullPathNameA,
		dict.SID("GetFullPathNameW"):            GetFullPathNameW,
		dict.SID("GetLastError"):                GetLastError,
		dict.SID("GetProcAddress"):              GetProcAddress,
		dict.SID("GetProcessHeap"):              GetProcessHeap,
		dict.SID("GetSystemInfo"):               GetSystemInfo,
		dict.SID("GetSystemTime"):               GetSystemTime,
		dict.SID("GetSystemTimeAsFileTime"):     GetSystemTimeAsFileTime,
		dict.SID("GetTempPathA"):                GetTempPathA,
		dict.SID("GetTempPathW"):                GetTempPathW,
		dict.SID("GetTickCount"):                GetTickCount,
		dict.SID("GetVersionExA"):               GetVersionExA,
		dict.SID("GetVersionExW"):               GetVersionExW,
		dict.SID("HeapAlloc"):                   HeapAlloc,
		dict.SID("HeapCreate"):                  HeapCreate,
		dict.SID("HeapCompact"):                 HeapCompact,
		dict.SID("HeapDestroy"):                 HeapDestroy,
		dict.SID("HeapFree"):                    HeapFree,
		dict.SID("HeapReAlloc"):                 HeapReAlloc,
		dict.SID("HeapSize"):                    HeapSize,
		dict.SID("HeapValidate"):                HeapValidate,
		dict.SID("_InterlockedCompareExchange"): InterlockedCompareExchange,
		dict.SID("InitializeCriticalSection"):   InitializeCriticalSection,
		dict.SID("LoadLibraryA"):                LoadLibraryA,
		dict.SID("LoadLibraryW"):                LoadLibraryW,
		dict.SID("LocalFree"):                   LocalFree,
		dict.SID("LockFile"):                    LockFile,
		dict.SID("LockFileEx"):                  LockFileEx,
		dict.SID("LeaveCriticalSection"):        LeaveCriticalSection,
		dict.SID("MapViewOfFile"):               MapViewOfFile,
		dict.SID("MultiByteToWideChar"):         MultiByteToWideChar,
		dict.SID("OutputDebugStringA"):          OutputDebugStringA,
		dict.SID("OutputDebugStringW"):          OutputDebugStringW,
		dict.SID("QueryPerformanceCounter"):     QueryPerformanceCounter,
		dict.SID("ReadFile"):                    ReadFile,
		dict.SID("SetEndOfFile"):                SetEndOfFile,
		dict.SID("SetFilePointer"):              SetFilePointer,
		dict.SID("Sleep"):                       Sleep,
		dict.SID("SystemTimeToFileTime"):        SystemTimeToFileTime,
		dict.SID("UnlockFile"):                  UnlockFile,
		dict.SID("UnlockFileEx"):                UnlockFileEx,
		dict.SID("UnmapViewOfFile"):             UnmapViewOfFile,
		dict.SID("WaitForSingleObject"):         WaitForSingleObject,
		dict.SID("WaitForSingleObjectEx"):       WaitForSingleObjectEx,
		dict.SID("WideCharToMultiByte"):         WideCharToMultiByte,
		dict.SID("WriteFile"):                   WriteFile,
	})
}
