// Copyright 2017 The Virtual Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
//
// Code generated by running "go generate". DO NOT EDIT.

// +build !windows

package virtual

import (
	"fmt"
)

func winStub(name string) {
	panic(fmt.Errorf("%s not supported on linux", name))
}

// //sys:kernel32: BOOL   	AreFileApisANSI();
func (c *cpu) AreFileApisANSI() {
	winStub("AreFileApisANSI")
}

// //sys:kernel32: HANDLE 	CreateFileA(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
func (c *cpu) CreateFileA() {
	winStub("CreateFileA")
}

// //sys:kernel32: HANDLE 	CreateFileW(LPCWSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
func (c *cpu) CreateFileW() {
	winStub("CreateFileW")
}

// //sys:kernel32: HANDLE 	CreateFileMappingA(HANDLE hFile, LPSECURITY_ATTRIBUTES lpAttributes, DWORD flProtect, DWORD dwMaximumSizeHigh, DWORD dwMaximumSizeLow, LPCSTR lpName);
func (c *cpu) CreateFileMappingA() {
	winStub("CreateFileMappingA")
}

// //sys:kernel32: HANDLE 	CreateFileMappingW(HANDLE hFile, LPSECURITY_ATTRIBUTES lpAttributes, DWORD flProtect, DWORD dwMaximumSizeHigh, DWORD dwMaximumSizeLow, LPCWSTR lpName);
func (c *cpu) CreateFileMappingW() {
	winStub("CreateFileMappingW")
}

// //sys:kernel32: HANDLE 	CreateMutexW(LPSECURITY_ATTRIBUTES lpMutexAttributes, BOOL bInitialOwner, LPCTSTR lpName);
func (c *cpu) CreateMutexW() {
	winStub("CreateMutexW")
}

// //sys:kernel32: BOOL   	CloseHandle(HANDLE hObject);
func (c *cpu) CloseHandle() {
	winStub("CloseHandle")
}

// //sys:kernel32: void   	DeleteCriticalSection(LPCRITICAL_SECTION lpCriticalSection);
func (c *cpu) DeleteCriticalSection() {
	winStub("DeleteCriticalSection")
}

// //sys:kernel32: BOOL   	DeleteFileA(LPCTSTR lpFileName);
func (c *cpu) DeleteFileA() {
	winStub("DeleteFileA")
}

// //sys:kernel32: BOOL   	DeleteFileW(LPCTSTR lpFileName);
func (c *cpu) DeleteFileW() {
	winStub("DeleteFileW")
}

// //sys:kernel32: void   	EnterCriticalSection(LPCRITICAL_SECTION lpCriticalSection);
func (c *cpu) EnterCriticalSection() {
	winStub("EnterCriticalSection")
}

// //sys:kernel32: BOOL   	FlushFileBuffers(HANDLE hFile);
func (c *cpu) FlushFileBuffers() {
	winStub("FlushFileBuffers")
}

// //sys:kernel32: BOOL     FlushViewOfFile(LPCVOID lpBaseAddress, SIZE_T dwNumberOfBytesToFlush);
func (c *cpu) FlushViewOfFile() {
	winStub("FlushViewOfFile")
}

// //sys:kernel32: DWORD  	FormatMessageA(DWORD dwFlags, LPCVOID lpSource, DWORD dwMessageId, DWORD dwLanguageId, LPTSTR lpBuffer, DWORD nSize, va_list* Arguments);
func (c *cpu) FormatMessageA() {
	winStub("FormatMessageA")
}

// //sys:kernel32: DWORD  	FormatMessageW(DWORD dwFlags, LPCVOID lpSource, DWORD dwMessageId, DWORD dwLanguageId, LPTSTR lpBuffer, DWORD nSize, va_list* Arguments);
func (c *cpu) FormatMessageW() {
	winStub("FormatMessageW")
}

// //sys:kernel32: BOOL   	FreeLibrary(HMODULE hModule);
func (c *cpu) FreeLibrary() {
	winStub("FreeLibrary")
}

// //sys:kernel32: DWORD  	GetCurrentProcessId();
func (c *cpu) GetCurrentProcessId() {
	winStub("GetCurrentProcessId")
}

// //sys:kernel32: BOOL   	GetDiskFreeSpaceA(LPCTSTR lpRootPathName, LPDWORD lpSectorsPerCluster, LPDWORD lpBytesPerSector, LPDWORD lpNumberOfFreeClusters, LPDWORD lpTotalNumberOfClusters);
func (c *cpu) GetDiskFreeSpaceA() {
	winStub("GetDiskFreeSpaceA")
}

// //sys:kernel32: BOOL   	GetDiskFreeSpaceW(LPCTSTR lpRootPathName, LPDWORD lpSectorsPerCluster, LPDWORD lpBytesPerSector, LPDWORD lpNumberOfFreeClusters, LPDWORD lpTotalNumberOfClusters);
func (c *cpu) GetDiskFreeSpaceW() {
	winStub("GetDiskFreeSpaceW")
}

// //sys:kernel32: BOOL   	GetFileAttributesExW(LPCTSTR lpFileName, GET_FILEEX_INFO_LEVELS fInfoLevelId, LPVOID lpFileInformation);
func (c *cpu) GetFileAttributesExW() {
	winStub("GetFileAttributesExW")
}

// //sys:kernel32: DWORD  	GetFileAttributesA(LPCTSTR lpFileName);
func (c *cpu) GetFileAttributesA() {
	winStub("GetFileAttributesA")
}

// //sys:kernel32: DWORD  	GetFileAttributesW(LPCTSTR lpFileName);
func (c *cpu) GetFileAttributesW() {
	winStub("GetFileAttributesW")
}

// //sys:kernel32: DWORD  	GetFileSize(HANDLE hFile, LPDWORD lpFileSizeHigh);
func (c *cpu) GetFileSize() {
	winStub("GetFileSize")
}

// //sys:kernel32: DWORD  	GetFullPathNameA( LPCTSTR lpFileName, DWORD nBufferLength, LPTSTR lpBuffer, LPTSTR* lpFilePart);
func (c *cpu) GetFullPathNameA() {
	winStub("GetFullPathNameA")
}

// //sys:kernel32: DWORD  	GetFullPathNameW( LPCTSTR lpFileName, DWORD nBufferLength, LPTSTR lpBuffer, LPTSTR* lpFilePart);
func (c *cpu) GetFullPathNameW() {
	winStub("GetFullPathNameW")
}

// //sys:kernel32: FARPROC 	GetProcAddress(HMODULE hModule, LPCSTR lpProcName);
func (c *cpu) GetProcAddress() {
	winStub("GetProcAddress")
}

// //sys:kernel32: HANDLE   GetProcessHeap();
func (c *cpu) GetProcessHeap() {
	winStub("GetProcessHeap")
}

// //sys:kernel32: void   	GetSystemInfo(LPSYSTEM_INFO lpSystemInfo);
func (c *cpu) GetSystemInfo() {
	winStub("GetSystemInfo")
}

// //sys:kernel32: void   	GetSystemTime(LPSYSTEMTIME lpSystemTime);
func (c *cpu) GetSystemTime() {
	winStub("GetSystemTime")
}

// //sys:kernel32: void     GetSystemTimeAsFileTime(LPFILETIME lpSystemTimeAsFileTime);
func (c *cpu) GetSystemTimeAsFileTime() {
	winStub("GetSystemTimeAsFileTime")
}

// //sys:kernel32: DWORD    GetTempPathA(DWORD nBufferLength, LPTSTR lpBuffer);
func (c *cpu) GetTempPathA() {
	winStub("GetTempPathA")
}

// //sys:kernel32: DWORD    GetTempPathW(DWORD nBufferLength, LPTSTR lpBuffer);
func (c *cpu) GetTempPathW() {
	winStub("GetTempPathW")
}

// //sys:kernel32: DWORD  	GetTickCount();
func (c *cpu) GetTickCount() {
	winStub("GetTickCount")
}

// //sys:kernel32: BOOL   	GetVersionExA(LPOSVERSIONINFO lpVersionInfo);
func (c *cpu) GetVersionExA() {
	winStub("GetVersionExA")
}

// //sys:kernel32: BOOL   	GetVersionExW(LPOSVERSIONINFO lpVersionInfo);
func (c *cpu) GetVersionExW() {
	winStub("GetVersionExW")
}

// //sys:kernel32: LPVOID 	HeapAlloc(HANDLE hHeap, DWORD dwFlags, SIZE_T dwBytes);
func (c *cpu) HeapAlloc() {
	winStub("HeapAlloc")
}

// //sys:kernel32: SIZE_T   HeapCompact(HANDLE hHeap, DWORD dwFlags);
func (c *cpu) HeapCompact() {
	winStub("HeapCompact")
}

// //sys:kernel32: HANDLE   HeapCreate(DWORD flOptions, SIZE_T dwInitialSize, SIZE_T dwMaximumSize);
func (c *cpu) HeapCreate() {
	winStub("HeapCreate")
}

// //sys:kernel32: BOOL     HeapDestroy(HANDLE hHeap);
func (c *cpu) HeapDestroy() {
	winStub("HeapDestroy")
}

// //sys:kernel32: BOOL     HeapFree(HANDLE hHeap, DWORD dwFlags, LPVOID lpMem);
func (c *cpu) HeapFree() {
	winStub("HeapFree")
}

// //sys:kernel32: LPVOID   HeapReAlloc(HANDLE hHeap, DWORD dwFlags, LPVOID lpMem, SIZE_T dwBytes);
func (c *cpu) HeapReAlloc() {
	winStub("HeapReAlloc")
}

// //sys:kernel32: SIZE_T   HeapSize(HANDLE hHeap, DWORD dwFlags, LPCVOID lpMem);
func (c *cpu) HeapSize() {
	winStub("HeapSize")
}

// //sys:kernel32: BOOL     HeapValidate(HANDLE hHeap, DWORD dwFlags, LPCVOID lpMem);
func (c *cpu) HeapValidate() {
	winStub("HeapValidate")
}

// //sys:kernel32: void   	InitializeCriticalSection(LPCRITICAL_SECTION lpCriticalSection);
func (c *cpu) InitializeCriticalSection() {
	winStub("InitializeCriticalSection")
}

// //sys:kernel32: void   	LeaveCriticalSection(LPCRITICAL_SECTION lpCriticalSection);
func (c *cpu) LeaveCriticalSection() {
	winStub("LeaveCriticalSection")
}

// //sys:kernel32: HMODULE  LoadLibraryA(LPCTSTR lpFileName);
func (c *cpu) LoadLibraryA() {
	winStub("LoadLibraryA")
}

// //sys:kernel32: HMODULE  LoadLibraryW(LPCTSTR lpFileName);
func (c *cpu) LoadLibraryW() {
	winStub("LoadLibraryW")
}

// //sys:kernel32: HLOCAL 	LocalFree(HLOCAL hMem);
func (c *cpu) LocalFree() {
	winStub("LocalFree")
}

// //sys:kernel32: BOOL     LockFile(HANDLE hFile, DWORD dwFileOffsetLow, DWORD dwFileOffsetHigh, DWORD nNumberOfBytesToLockLow, DWORD nNumberOfBytesToLockHigh);
func (c *cpu) LockFile() {
	winStub("LockFile")
}

// //sys:kernel32: BOOL   	LockFileEx(HANDLE hFile, DWORD dwFlags, DWORD dwReserved, DWORD nNumberOfBytesToLockLow, DWORD nNumberOfBytesToLockHigh, LPOVERLAPPED lpOverlapped);
func (c *cpu) LockFileEx() {
	winStub("LockFileEx")
}

// //sys:kernel32: LPVOID   MapViewOfFile(HANDLE hFileMappingObject, DWORD dwDesiredAccess, DWORD dwFileOffsetHigh, DWORD dwFileOffsetLow, SIZE_T dwNumberOfBytesToMap);
func (c *cpu) MapViewOfFile() {
	winStub("MapViewOfFile")
}

// //sys:kernel32: int 	  	MultiByteToWideChar(UINT CodePage, DWORD dwFlags, LPCSTR lpMultiByteStr,	int cbMultiByte, LPWSTR lpWideCharStr, int cchWideChar);
func (c *cpu) MultiByteToWideChar() {
	winStub("MultiByteToWideChar")
}

// //sys:kernel32: void     OutputDebugStringA(LPCTSTR lpOutputString);
func (c *cpu) OutputDebugStringA() {
	winStub("OutputDebugStringA")
}

// //sys:kernel32: void     OutputDebugStringW(LPCTSTR lpOutputString);
func (c *cpu) OutputDebugStringW() {
	winStub("OutputDebugStringW")
}

// //sys:kernel32: BOOL   	QueryPerformanceCounter(LARGE_INTEGER* lpPerformanceCount);
func (c *cpu) QueryPerformanceCounter() {
	winStub("QueryPerformanceCounter")
}

// //sys:kernel32: BOOL   	ReadFile(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);
func (c *cpu) ReadFile() {
	winStub("ReadFile")
}

// //sys:kernel32: BOOL     SetEndOfFile(HANDLE hFile);
func (c *cpu) SetEndOfFile() {
	winStub("SetEndOfFile")
}

// //sys:kernel32: DWORD    SetFilePointer(HANDLE hFile, LONG lDistanceToMove, PLONG lpDistanceToMoveHigh, DWORD dwMoveMethod);
func (c *cpu) SetFilePointer() {
	winStub("SetFilePointer")
}

// //sys:kernel32: void     Sleep(DWORD dwMilliseconds);
func (c *cpu) Sleep() {
	winStub("Sleep")
}

// //sys:kernel32: BOOL     SystemTimeToFileTime(SYSTEMTIME* lpSystemTime, LPFILETIME lpFileTime);
func (c *cpu) SystemTimeToFileTime() {
	winStub("SystemTimeToFileTime")
}

// //sys:kernel32: BOOL     UnlockFile(HANDLE hFile, DWORD dwFileOffsetLow, DWORD dwFileOffsetHigh, DWORD nNumberOfBytesToUnlockLow, DWORD nNumberOfBytesToUnlockHigh);
func (c *cpu) UnlockFile() {
	winStub("UnlockFile")
}

// //sys:kernel32: BOOL   	UnlockFileEx(HANDLE hFile, DWORD dwReserved, DWORD nNumberOfBytesToUnlockLow, DWORD nNumberOfBytesToUnlockHigh, LPOVERLAPPED lpOverlapped);
func (c *cpu) UnlockFileEx() {
	winStub("UnlockFileEx")
}

// //sys:kernel32: BOOL     UnmapViewOfFile(LPCVOID lpBaseAddress);
func (c *cpu) UnmapViewOfFile() {
	winStub("UnmapViewOfFile")
}

// //sys:kernel32: DWORD    WaitForSingleObject(HANDLE hHandle, DWORD dwMilliseconds);
func (c *cpu) WaitForSingleObject() {
	winStub("WaitForSingleObject")
}

// //sys:kernel32: DWORD    WaitForSingleObjectEx(HANDLE hHandle, DWORD dwMilliseconds, BOOL bAlertable);
func (c *cpu) WaitForSingleObjectEx() {
	winStub("WaitForSingleObjectEx")
}

// //sys:kernel32: int    	WideCharToMultiByte(UINT CodePage, DWORD dwFlags, LPCWSTR lpWideCharStr, int cchWideChar, LPSTR lpMultiByteStr, int cbMultiByte, LPCSTR lpDefaultChar, LPBOOL lpUsedDefaultChar);
func (c *cpu) WideCharToMultiByte() {
	winStub("WideCharToMultiByte")
}

// //sys:kernel32: BOOL   	WriteFile(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);
func (c *cpu) WriteFile() {
	winStub("WriteFile")
}
